import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const projects = trpc.project.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {projects.data?.map((p) => (
          <p key={p.id}>{p.name}</p>
        ))}
      </main>
    </>
  );
};

export default Home;
